Fix missing function declarations when building tests
Fix these compiler warnings by declaring test_exit() and test_main()
regardless of whether TEST_NO_WRAPPERS is defined:

test-cmdline.c: In function ‘send_ioctl’:
test-cmdline.c:268:2: warning: implicit declaration of function ‘test_exit’ [-Wimplicit-function-declaration]
  test_exit(0);
  ^
test-common.c: In function ‘test_cmdline’:
test-common.c:361:21: warning: implicit declaration of function ‘test_main’ [-Wimplicit-function-declaration]
  rc = rc ? rc - 1 : test_main(argc, argv);
                     ^

Signed-off-by: Ben Hutchings <ben@decadent.org.uk>